react-1122-skill-map-forms-filter-issue
nerubia/kh360-react pull request #1124
Opened 2024-06-03 06:16 UTC by chadiegilnerubia

Ticket ID:
Skill Map Forms and Add Project - filter issue in Add / Select Skills screen
[#1122](https://github.com/nerubia/kh360-react/issues/1122)

2024-06-04 05:05 UTC, gborgonia-ir requested changes
should also fix on Project: Add Skills screen

2024-06-04 05:18 UTC, chadiegilnerubia commented
> should also fix on Project: Add Skills screen

done :3

2024-06-07 01:46 UTC, jatnerubia approved these changes
Cool

2024-06-07 03:34 UTC, gborgonia-ir approved these changes

2024-06-07 03:34 UTC, merged