add requested layout changes for view evaluation screen
nerubia/kh360-react pull request #119
Opened 2023-11-10 08:43 UTC by emmaacha

Ticket ID: [Create View Evaluation Administration Screen#40](https://github.com/nerubia/kh360-react/issues/40)

2023-11-10 08:51 UTC, jatnerubia requested changes
just a few changes ^^

2023-11-10 08:51 UTC, jatnerubia commented on src/features/admin/evaluation-administrations/[id]/ViewEvaluationHeader.tsx
> +              size='medium'
default is medium 🤔

2023-11-10 08:51 UTC, jatnerubia commented on src/redux/slices/evaluationAdministrationSlice.ts
> +export const deleteEvaluationAdminsitration = createAsyncThunk(
typo 🤔

2023-11-13 04:49 UTC, Dev-Nino approved these changes

2023-11-13 05:18 UTC, jatnerubia approved these changes
Nice

2023-11-13 05:18 UTC, merged