update: skill dropdown sorting
nerubia/kh360-react pull request #1194
Opened 2024-06-19 01:45 UTC by jatnerubia

Ticket ID: [Skill Map Search - Update Skill dropdown component and values](https://github.com/orgs/nerubia/projects/18/views/2?pane=issue&itemId=66713861)

2024-06-19 03:52 UTC, gborgonia-ir requested changes
putting this on hold, will confirm with sheila

2024-06-20 02:44 UTC, gborgonia-ir commented
@jatnerubia confirmed with sheila, for category sort by sequence number only. then for skills sort alphabetically. let me know if current PR is still required. thanksomuch

2024-06-20 07:38 UTC, chadiegilnerubia approved these changes

2024-06-20 07:53 UTC, chadiegilnerubia approved these changes

2024-06-21 04:12 UTC, gborgonia-ir approved these changes

2024-06-21 04:12 UTC, merged