react-1269-skill-map-result-add-comment-section
nerubia/kh360-react pull request #1276
Opened 2024-07-01 07:53 UTC by chadiegilnerubia

Ticket ID:
Skill Map Results - add comments section
[#1269](https://github.com/nerubia/kh360-react/issues/1269)

2024-07-02 00:25 UTC, jatnerubia requested changes
Just a minor change ^^

2024-07-02 00:25 UTC, jatnerubia commented on src/features/admin/skill-map-results/skill-map-results-list-table.tsx
> +        .filter((s) => s.skill_map_results.length > 0 && s.skill_map_results[0].comments !== "")
Move this to the sort util

2024-07-02 00:39 UTC, chadiegilnerubia commented on src/features/admin/skill-map-results/skill-map-results-list-table.tsx
> +        .filter((s) => s.skill_map_results.length > 0 && s.skill_map_results[0].comments !== "")
done :3

2024-07-03 04:26 UTC, gborgonia-ir approved these changes

2024-07-04 05:39 UTC, jatnerubia approved these changes
Cool

2024-07-04 05:39 UTC, merged