added more options dropdown
nerubia/kh360-react pull request #157
Opened 2023-11-20 08:27 UTC by jatnerubia

Ticket ID: [Change EDIT button, add Close and Cancel actions in View Eval Admin Screen](https://github.com/orgs/nerubia/projects/18/views/2?pane=issue&itemId=44918323)

2023-11-20 09:50 UTC, emmaacha commented on __tests__/pages/admin/evaluation-administrations/[id]/view_evaluation.spec.ts
> +      await expect(page.getByRole("button", { name: "More options" })).toBeVisible()
I think this is "`More actions`"?

2023-11-20 10:11 UTC, emmaacha requested changes
Just a few nits

2023-11-20 10:11 UTC, emmaacha commented on src/features/admin/evaluation-administrations/[id]/ViewEvaluationHeader.tsx
> +                <Button>More options</Button>
Also, could we add an arrow icon on the right like this?
![image](https://github.com/nerubia/kh360-react/assets/91468846/974401a1-857b-4156-9471-ac5e1bd02559)

2023-11-20 23:29 UTC, jatnerubia commented
@emmaacha done ^^

2023-11-21 01:32 UTC, emmaacha approved these changes
lgtm! 🚀

2023-11-22 02:49 UTC, Dev-Nino approved these changes

2023-11-22 02:49 UTC, merged