added create external evaluator
nerubia/kh360-react pull request #164
Opened 2023-11-21 02:06 UTC by jatnerubia

Ticket ID: [Add External Evaluators Screen](https://github.com/orgs/nerubia/projects/18/views/2?pane=issue&itemId=44541085)

2023-11-21 10:46 UTC, emmaacha requested changes
Typo for file name `create-external-evaluator.tsx`

2023-11-21 23:26 UTC, jatnerubia commented
@emmaacha done ^^

2023-11-22 02:53 UTC, Dev-Nino approved these changes

2023-11-22 05:46 UTC, emmaacha approved these changes

2023-11-22 06:01 UTC, merged