update performance evaluation form layout
nerubia/kh360-react pull request #166
Opened 2023-11-21 03:34 UTC by emmaacha

Ticket ID: [Performance Evaluation Form Changes#159](https://github.com/nerubia/kh360-react/issues/159)

2023-11-21 05:05 UTC, jatnerubia requested changes
just a few changes ^^

2023-11-21 05:05 UTC, jatnerubia commented on src/utils/formatDate.ts
> +export const formatDateRange = (start_date?: string, end_date?: string) => {
I  also have an update for this. Can you check to see if we can reuse it. [here](https://github.com/nerubia/kh360-react/pull/165/files#diff-3290e87c24e27923abe4a89682818bc0169238f9c4784ab4545dd448c0951415)

2023-11-22 05:44 UTC, jatnerubia requested changes
^^

2023-11-22 05:44 UTC, jatnerubia commented on src/features/evaluations/[id]/EvaluationsCriteria.tsx
> +              <h1>
we should have one `h1` per page

2023-11-22 05:44 UTC, jatnerubia commented on src/features/evaluations/[id]/EvaluationsCriteria.tsx
> +            <h1 className='mb-4 text-sm'>
we should have one `h1` per page

2023-11-22 06:18 UTC, jatnerubia approved these changes
Nice

2023-11-22 08:35 UTC, Dev-Nino approved these changes

2023-11-22 08:35 UTC, merged