add requested changes for NA comments
nerubia/kh360-react pull request #202
Opened 2023-11-28 03:09 UTC by emmaacha

Ticket IDs:

- [Evaluation Form - require comment if answer is NA#170](https://github.com/nerubia/kh360-react/issues/170#issuecomment-1825250154)
- [Evaluation Form - if at least 75% of the answers are the highest rating, please require comment.#175](https://github.com/nerubia/kh360-react/issues/175#issuecomment-1826930598)
-  [Evaluation Form - if at least 75% of the answers are the lowest rating, please require comment.#178](https://github.com/nerubia/kh360-react/issues/178#issuecomment-1826934012)

BE PR: [update seed for rating templates #186](https://github.com/nerubia/kh360-nodejs/pull/186)

2023-11-28 04:43 UTC, Dev-Nino approved these changes

2023-11-29 00:14 UTC, jatnerubia requested changes
^^

2023-11-29 00:14 UTC, jatnerubia commented on src/components/dialog/Dialog.tsx
> +function Dialog({ open, children, width = "md:w-[500px]" }: DialogProps) {
Let's create a variant of this

2023-11-29 06:19 UTC, jatnerubia approved these changes
Nice

2023-11-29 06:19 UTC, merged