add evaluation results menu item in sidebar
nerubia/kh360-react pull request #362
Opened 2023-12-18 09:05 UTC by emmaacha

Ticket ID: [Evaluation Results - add new menu item for Evaluation Results #351](https://github.com/nerubia/kh360-react/issues/351)

BE PR: [update auth add user_type in response #327](https://github.com/nerubia/kh360-nodejs/pull/327)

2023-12-18 23:46 UTC, jatnerubia requested changes
^^

2023-12-18 23:46 UTC, jatnerubia commented on src/components/ui/icon/icons.ts
> +  ListChecks: lazy(async () => await import("./icons/list-checks-icon")),
fix order

2023-12-19 02:25 UTC, emmaacha commented on src/components/ui/icon/icons.ts
> +  ListChecks: lazy(async () => await import("./icons/list-checks-icon")),
Done ^^

2023-12-19 03:33 UTC, jatnerubia approved these changes
Cool

2023-12-19 04:36 UTC, Dev-Nino approved these changes

2023-12-19 04:36 UTC, merged