add evaluation results screen
nerubia/kh360-react pull request #386
Opened 2023-12-21 04:50 UTC by emmaacha

Ticket ID: [Create Evaluation Results screen#352](https://github.com/nerubia/kh360-react/issues/352)

BE PR:

2023-12-21 09:00 UTC, chadiegilnerubia approved these changes
Good :1st_place_medal:

2023-12-22 00:49 UTC, jatnerubia requested changes
just a few changes ^^

2023-12-22 00:49 UTC, jatnerubia commented on src/features/evaluation-results/[id]/evaluation-results-footer.tsx
> +    navigate(`/my-evaluations`)
I think this should redirect to the evaluation results list screen 🤔

2023-12-22 00:49 UTC, jatnerubia commented on src/features/evaluation-results/[id]/evaluation-results-comments.tsx
Shouldn't this be named 'view'? 🤔

2023-12-22 00:49 UTC, jatnerubia commented on src/features/evaluation-results/[id]/evaluation-results-footer.tsx
Shouldn't this be named 'view'? 🤔

2023-12-22 00:49 UTC, jatnerubia commented on src/features/evaluation-results/[id]/evaluation-results-header.tsx
Shouldn't this be named 'view'? 🤔

2023-12-22 00:49 UTC, jatnerubia commented on src/features/evaluation-results/[id]/evaluation-results-table.tsx
Shouldn't this be named 'view'? 🤔

2023-12-22 00:49 UTC, jatnerubia commented on src/routes/bod-user-route.tsx
change to CM? 🤔

2023-12-22 01:37 UTC, emmaacha commented on src/routes/bod-user-route.tsx
Yep, change for this was made in the other PR, will update this branch, thanks!

2023-12-22 01:46 UTC, emmaacha commented
Done ^^

2023-12-22 02:54 UTC, jatnerubia approved these changes
Cool

2023-12-22 02:54 UTC, merged