added test cases for evaluation form in mobile view
nerubia/kh360-react pull request #392
Opened 2023-12-22 08:20 UTC by chadiegilnerubia

Additional Test cases for evaluation form in mobile view

2023-12-22 08:23 UTC, jatnerubia requested changes
^^

2023-12-22 08:23 UTC, jatnerubia commented on __tests__/pages/evaluations/[id]/evaluations.spec.ts
> +      // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
avoid using this

2023-12-22 09:30 UTC, chadiegilnerubia commented on __tests__/pages/evaluations/[id]/evaluations.spec.ts
> +      // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
done thanks

2023-12-22 12:16 UTC, emmaacha approved these changes
lgtm 🚀

2023-12-28 06:42 UTC, jatnerubia approved these changes
🚀

2023-12-29 06:53 UTC, merged