397 message template screen
nerubia/kh360-react pull request #410
Opened 2023-12-28 07:02 UTC by gborgonia-ir

Ticket ID: #397

2023-12-28 07:18 UTC, jatnerubia requested changes
^^

2023-12-28 07:18 UTC, jatnerubia commented on src/components/ui/icon/icons/message-icon.tsx
> +export default function GanttChartIcon({ size }: { size: number }) {
typo

2023-12-28 07:58 UTC, emmaacha approved these changes

2023-12-28 07:58 UTC, emmaacha commented on src/features/admin/email-templates/email-templates-filter.tsx
> +  const [is_default, setDefault] = useState<string>(searchParams.get("defult") ?? "all")
Typo for `default`

2023-12-28 08:00 UTC, emmaacha requested changes
Kindly fix typo, misclicked approve for this change request 😅

2023-12-28 08:33 UTC, jatnerubia approved these changes
Cool

2023-12-29 02:06 UTC, emmaacha approved these changes

2023-12-29 02:13 UTC, merged