400 edit msg template latest
nerubia/kh360-react pull request #485
Opened 2024-01-09 03:18 UTC by gborgonia-ir

Ticket ID:
Ticket ID:
[Create Edit Message Template screen](https://github.com/nerubia/kh360-react/issues/400)

2024-01-09 05:17 UTC, jatnerubia requested changes
just a few changes ^^

2024-01-09 05:17 UTC, jatnerubia commented on src/features/admin/email-templates/[id]/edit/edit-email-template-form.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
avoid using `any`

2024-01-09 05:17 UTC, jatnerubia commented on src/features/admin/email-templates/[id]/edit/edit-email-template-form.tsx
can you reuse the email template form?

2024-01-09 05:17 UTC, jatnerubia commented on src/features/admin/email-templates/email-template-form/email-template-form.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
avoid using `any`

2024-01-10 01:31 UTC, jatnerubia requested changes
just a few changes ^^

also please update the name [here](https://github.com/nerubia/kh360-react/blob/beta/src/pages/admin/email-templates/email-templates.tsx)

2024-01-10 01:31 UTC, jatnerubia commented on src/pages/admin/email-templates/[id]/edit/edit-email-template.tsx
> +export default function EditEvaluation() {
update the component name

2024-01-10 02:19 UTC, jatnerubia approved these changes
Cool

2024-01-10 02:21 UTC, emmaacha approved these changes

2024-01-10 02:21 UTC, merged