kh360-react-eval-screen-select-limited-10-items
nerubia/kh360-react pull request #525
Opened 2024-01-15 09:32 UTC by chadiegilnerubia

Ticket ID:
[Evaluation Result: Evaluation Administration Filter - All Closed and Published should be display in the dropdown selection#504](https://github.com/nerubia/kh360-react/issues/504)

2024-01-18 10:12 UTC, gborgonia-ir approved these changes

2024-01-18 10:23 UTC, emmaacha requested changes

2024-01-18 10:23 UTC, emmaacha commented on src/components/ui/select/custom-select-infinite.tsx
> +  hastNextPage: boolean
Typo for `hasNextPage`

2024-01-18 10:23 UTC, emmaacha commented on src/components/ui/select/custom-select-infinite.tsx
> +  const hasMore = totalEvalItems > 10 || hastNextPage
Typo for `hasNextPage`

2024-01-18 10:23 UTC, emmaacha commented on src/features/evaluation-results/evaluation-results-list-filter.tsx
> +  const [hastNextPage, setHasNextPage] = useState<boolean>(false)
Typo for `hasNextPage`

2024-01-18 10:23 UTC, emmaacha commented on src/features/evaluation-results/evaluation-results-list-filter.tsx
> +    if (hastNextPage) {
Typo for `hasNextPage`

2024-01-18 10:23 UTC, emmaacha commented on src/features/evaluation-results/evaluation-results-list-filter.tsx
> +                  hastNextPage
Typo for `hasNextPage`

2024-01-19 07:10 UTC, chadiegilnerubia commented on src/components/ui/select/custom-select-infinite.tsx
> +  hastNextPage: boolean
Donee thanks :3

2024-01-19 08:19 UTC, emmaacha approved these changes

2024-01-22 02:26 UTC, merged