Kh360 react 442 evaluation admin screen mobile view
nerubia/kh360-react pull request #530
Opened 2024-01-17 01:24 UTC by chadiegilnerubia

Ticket ID:
View Evaluation Administration Screen - adjust to make it mobile responsive
[#442](https://github.com/nerubia/kh360-react/issues/442)

2024-01-18 10:20 UTC, gborgonia-ir approved these changes

2024-01-18 10:27 UTC, emmaacha requested changes
Please fix conflicts and rebase, thank you!

2024-01-22 02:45 UTC, emmaacha requested changes
Kindly change commit message for clearer description of commit, thanks!

2024-01-23 04:52 UTC, chadiegilnerubia commented
> Kindly change commit message for clearer description of commit, thanks!

done :3

2024-01-23 05:55 UTC, emmaacha approved these changes

2024-01-23 05:55 UTC, merged