add tests for edit evaluation administrations screen
nerubia/kh360-react pull request #61
Opened 2023-10-31 02:04 UTC by emmaacha

2023-10-31 02:30 UTC, Dev-Nino approved these changes

2023-10-31 05:14 UTC, jatnerubia reviewed
just a few changes

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +          evaluation_results: [
not needed 🤔

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +      await expect(page.getByPlaceholder("Evaluation name")).toBeVisible()
should check the input value

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +
same

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +
same

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +          evaluation_results: [
not needed

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +          evaluation_results: [
same

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +          evaluation_results: [
same

2023-10-31 05:14 UTC, jatnerubia commented on __tests__/pages/admin/evaluation-administrations/[id]/edit/edit_evaluation.spec.ts
> +          evaluation_results: [
same

2023-11-03 02:41 UTC, jatnerubia requested changes
just a few changes

2023-11-06 02:01 UTC, jatnerubia approved these changes
Nice

2023-11-06 02:02 UTC, merged