kh360-react-673-lazy-load-evaluation-templates
nerubia/kh360-react pull request #697
Opened 2024-02-13 02:21 UTC by chadiegilnerubia

Ticket ID:
Implement lazy loading on Evaluation Templates
[#673](https://github.com/nerubia/kh360-react/issues/673)

2024-02-13 05:26 UTC, gborgonia-ir commented on src/features/admin/evaluation-templates/evaluation-templates-dialog.tsx
> +const EmailTemplatesDialog: React.FC<EvaluationTemplateDialogProps> = ({
rename also thi

2024-02-13 05:26 UTC, gborgonia-ir commented on src/features/admin/evaluation-templates/evaluation-templates-table.tsx
> +const EmailTemplatesDialog = lazy(
rename also this

2024-02-13 05:31 UTC, chadiegilnerubia commented on src/features/admin/evaluation-templates/evaluation-templates-dialog.tsx
> +const EmailTemplatesDialog: React.FC<EvaluationTemplateDialogProps> = ({
Owws mb okey2

2024-02-13 06:31 UTC, gborgonia-ir approved these changes

2024-02-14 05:49 UTC, emmaacha requested changes

2024-02-14 05:49 UTC, emmaacha commented on src/features/admin/evaluation-templates/evaluation-templates-dialog.tsx
> +    <Dialog open={open} size={size} maxWidthMin={maxWidthMin}>
Please use custom dialog component here

2024-02-14 06:51 UTC, merged