react-962-survey-results-ui-enchancement
nerubia/kh360-react pull request #970
Opened 2024-04-03 06:41 UTC by chadiegilnerubia

Ticket ID:
Survey Results - UI Enhancement
[#962](https://github.com/nerubia/kh360-react/issues/962)

2024-04-03 07:00 UTC, gborgonia-ir commented on src/features/admin/survey-results/[id]/tables/respondent-view-table.tsx
> +  console.log("survey_results", survey_results)
can pls remove console

2024-04-03 07:47 UTC, chadiegilnerubia commented on src/features/admin/survey-results/[id]/tables/respondent-view-table.tsx
> +  console.log("survey_results", survey_results)
ops xD

2024-04-03 08:52 UTC, emmaacha approved these changes

2024-04-03 13:28 UTC, emmaacha requested changes
Hello! I added the needed changes for this ticket (updated backend too), kindly just add or improve some minor details like the amount should be in currency form (comma in between numbers), and the column widths, etc.). Thanks!

2024-04-04 01:44 UTC, gborgonia-ir commented on src/features/admin/survey-results/[id]/tables/respondent-view-table.tsx
> +                            <Badge variant='green' size='small'>
pls modify to show variant based on status. you can check getEvaluationResultStatusVariant

2024-04-04 01:47 UTC, gborgonia-ir commented on src/features/admin/survey-results/[id]/tables/respondent-view-table.tsx
> +                  <p className='text-primary-500 font-bold text-lg'>Companions</p>
also can pls hide if companion_survey_results is empty

2024-04-04 06:50 UTC, emmaacha approved these changes

2024-04-04 06:58 UTC, gborgonia-ir approved these changes

2024-04-04 07:03 UTC, merged