react-897-side-menu-accordion-toggle
nerubia/kh360-react pull request #999
Opened 2024-04-11 03:34 UTC by chadiegilnerubia

Ticket ID:
Side Menu Accordion should be hidden when clicking back
[#897](https://github.com/nerubia/kh360-react/issues/897)

2024-04-11 08:42 UTC, emmaacha requested changes

2024-04-11 08:42 UTC, emmaacha commented on src/components/shared/sidebar/sidebar.tsx
> +                        <Icon size={isMediumSize ? "extraSmall" : "medium"} icon='ChevronDown' />
Arrow icon should be up if menu is open

2024-04-11 08:42 UTC, emmaacha commented on src/components/shared/sidebar/sidebar.tsx
> +                        <Icon size={isMediumSize ? "extraSmall" : "medium"} icon='ChevronRight' />
and down if menu is not open

2024-04-12 02:27 UTC, chadiegilnerubia commented on src/components/shared/sidebar/sidebar.tsx
> +                        <Icon size={isMediumSize ? "extraSmall" : "medium"} icon='ChevronRight' />
done

2024-04-12 05:20 UTC, emmaacha approved these changes

2024-04-15 02:36 UTC, merged